params:
  seed: ${...seed}
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True

    space:
      continuous:
        
    mlp:
      units: [256, 128, 64] # 
      activation: relu
      #d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False}
  load_path: ${...checkpoint}

  config:
    name: ${resolve_default:FactoryTaskPegHolePick,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    #ppo: True
    #mixed_precision: True
    normalize_input: True
    #normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    #normalize_advantage: True
    gamma: 0.99
    init_alpha: 1
    alpha_lr: 0.005
    actor_lr: 0.0005
    critic_lr: 0.0005
    critic_tau: 0.005
    #tau: 0.95
    #learning_rate: 1e-4
    #lr_schedule: fixed
    #schedule_type: standard
    #kl_threshold: 0.016
    score_to_win: 20000
    max_epochs: ${resolve_default:1024,${....max_iterations}}
    num_steps_per_episode: 
    num_warmup_steps: 10 # total number of warmup steps: num_actors * num_steps_per_episode
    save_best_after: 50
    save_frequency: 100
    batch_size: 512
    print_stats: True
    #target_entropy_coef:
    #grad_norm: 1.0 
    #truncate_grads: False
    #e_clip: 0.2
    #horizon_length: 120
    #mini_epochs: 8
    learnable_temperature: True
    replay_buffer_size: 1000000
    #critic_coef: 2
    #clip_value: True
    #seq_len: 4
    #bounds_loss_coef: 0.0001
